version: '3'
services:
  api:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: always
    user: node
    ports:
      - 3001:3001
    volumes:
      - /env/.env:./env
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../gestion-data:/data/db/